config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/team'
  post 'home/team' => 'home#team'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :common, :only => [:index, :team]  
  
  def common
      @hero_name = Faker::Superhero.name
      @hero_power = Faker::Superhero.power
      @hero_prefix = Faker::Superhero.prefix
      @corp_title = Faker::Name.title
      @corp_power = Faker::Company.bs
      @corp_power = @corp_power.titleize
      
      @bg_num= rand(1..2)
      @set_num = rand(1..2)
      
      @avatar = Faker::Avatar.image(@hero_name,"300x300","png","set#{@set_num.to_s}","bg#{@bg_num.to_s}")
  end
  
  def index
  end
  
  def team
    @team_number = params[:team_number].to_i
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create_team.html.erb
    <div class="row">
      </br>
        <div class="col-md-4">
            <%= form_tag home_team_path, :method => 'POST' do %>
            <%= select_tag(:team_number, options_for_select([
                          ['1',1],
                          ['2',2],
                          ['3',3],
                          ['4',4],
                          ['5',5],
                          ['6',6],
                          ['7',7],
                          ['8',8],
                          ['9',9],
                          ['10',10],
                          ]), class: 'form-control')  %>
            </br>
            <%= submit_tag 'Build Your Team', class: "btn btn-default" %>
            <% end %>
        </div> 
        <div class="col-md-4">
          
        </div>
        <div class="col-md-4">
          
        </div>
    </div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SUPER HERO NAME GENERATOR', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
          
        <li><%= link_to 'Home Page', root_path %> </li>
        <li><%= link_to 'Create A Team', home_team_path %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_show_team.html.erb
    <% @team_number.times do %>
    
    <div class="row">
      <div class="col-md-4">
         <img src="<%=Faker::Avatar.image(rand(1...1000),"300x300","png","set#{rand(1..2).to_s}","bg#{rand(1..2).to_s}") %>">
      </div>
      <div class="col-md-4">
        <h3>
          Superhero Name:</br>
          <span class="red"><%= Faker::Superhero.name %></span></br>
        </h3>
        
        <h3>
          Superhero Power:</br>
          <span class="red"><%= Faker::Superhero.power %></span></br>
        </h3>

        <h4>
        Your Undercover Day Job is :</br>
        <span class="corp_red"><%= Faker::Name.title %></span></br>
        Your Corporate Superpower is:</br>
        <span class="corp_red"><%= Faker::Company.bs %></span></br></br>
        </h4>
      </div>
      
      <div class="col-md-4"></div>
      
    </div>

    <hr>
    <% end %>

app/views/home/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to 'Click Here to Generate A New Superhero', root_path %></h3>
  </div>
  <div class="panel-body">
    <%= @name %>
  </div>
  <div class="panel-footer"><%= link_to 'Create A Whole Superhero Team', home_team_path %> </div>
</div>

app/views/home/team.html.erb
</br>


</br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title gray"><%if @team_number == 0 %>How Many Team Members Do You Want? <% else %> Your Superhero Team <% end %></h3>
  </div>
  <div class="panel-body">
    <% if @team_number > 0 %>
      <%= render 'home/show_team'%>
    <% else %>
      <%= render 'home/create_team'%>
    <% end %>
  </div>
  <div class="panel-footer"><%= link_to 'Create A Whole Superhero Team', home_team_path %> </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superhero Name Generator </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  
<%= render 'home/navbar' %>
<div class="container">
<%= yield %>
</div>
<br/><br/>
<br/><br/>
<center>
  Copyright © Nick Whitson - All Rights Reserved
</center>
</body>
</html>